version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
